source 'https://rubygems.org'

source 'http://localhost:9292' do
  gem 'some_private_gem'
  gem 'example' # NOTE: Simply removing this line will not work
end

# NOTE: Nor will simply adding the gem to the root
#
#   gem 'example'

# NOTE: To successfully recover, the source must first be forced
#
#   gem 'example', source: 'https://rubygems.org'
#
# and the lockfile regenerated (e.g. by running `bundle install`).
# Afterwards, the explicit source can be removed, or the line deleted entirely.
